### ISSUE TITLE
✴ [Spike] Evaluate the status of the project

### ISSUE THREAD

**Issue by nickkkccc** [tarantool/testcontainers-java-tarantool#100]
- [x] Evaluate code coverage by tests.
- [x] Evaluate code correctness (class-wise).
- [x] Do not use unnecessary modules implemented in the standard Java library.
- [ ] Perform code refactoring - rewrite the code into a more readable form.
- [x] Think about adding different kinds of containers.

**Comment by bitgorbovsky** [comment]
# Варианты путей пользователя

1. Нужно в тестах поднять Tarantool, как БД, один узел (database).
2. Нужно в тестах поднять несколько узлов Tarantool, с репликацией master-replica (database).
3. Нужно в тестах поднять приложение, написанное на Tarantool (application server).
4. Нужно в тестах поднять приложение, написанное на Tarantool, несколько узлов (application server).
5. Нужно в тестах поднять несколько узлов Tarantool, на которых крутится приложение на базе vshard, cartridge, запустить миграции. (database).
6. Нужно в тестах поднять несколько узлов Tarantool, на которых крутится приложение на базе vshard, cartridge, запустить миграции. (application server).
7. Нужно в тестах поднять коробочный продукт (TDG2, TarantoolDB). (database)

**Comment by bitgorbovsky** [comment]
Модулей/классов, которые можно убрать, используя только стандартную библиотеку - нет. Кандидатом был класс PathUtils, но при изучении оказалось, что средствами стандартной библиотеки не реализовать то, что он выполняет.

**Comment by bitgorbovsky** [comment]
Нет поддержки .dockerignore

**Comment by bitgorbovsky** [comment]
Класс TarantoolCartridgeContinaer не поддерживает получение портов для отдельных роутеров. "Кластер" в контейнере может запускаться с несколькими роутерами, доступны будут все порты кластера, но известен будет только один роутер, который задан либо по умолчанию (с портом 3301) либо через вызов функции withRouterPort().

Предлагается добавление метода для получения портов роутеров по именам.

```java
getRouterHost(String name)
getRouterPort(String name)
```

**Comment by bitgorbovsky** [comment]
Ранее directoryBinding использовался для сборки приложения cartridge внутри созданного и запущенного контейнера. Сейчас это используется только для сборки, при запуске контейнера с собранным приложением, нет смысла подключать папку с хоста.

Предлагается это убрать.

**Comment by bitgorbovsky** [comment]
Подключение томов (папок) в целом вызывает вопросы. Для чего оно нужно? Если нужно, чтобы подсунуть какие-то Lua-скрипты, то высока вероятность, что для этих скриптов также потребуются какие-то зависимости, которые необходимо подтягивать при сборке, то есть - это уже некоторое приложение.

В последних версиях testcontainers-java-tarantool всё вынесено на этап сборки образа, таким образом, логичнее предположить, что и Lua-скрипты, которые можно добавлять, также можно заносить в контенейр через сборку образа.

Если нужно подключить папку для какой-то другой цели, например, чтобы хранить данные Tarantool между перезапусками контейнера - то можно воспользоваться стандартными методами класса GenericContainer, например withFileSystemBind.

Но есть ли такая потребность на данный момент?

**Comment by bitgorbovsky** [comment]
Есть возможно конфигурировать количество памяти для одиночного контейнера (TarantoolContainer.withMemtxMemory(int memory)), но не возможности конфигурировать другие параметры.

Есть возможность задать эти параметры с помощью переменных окружения, при запуске контейнера, но есть параметры, которые можно менять в ходе работы, такой возможности нет.

Предлагается подумать над необходимостью добавления методов, позволяющих конфигурировать произвольные параметры.

**Comment by bitgorbovsky** [comment]
# Ручной анализ покрытия тестами

**TarantoolContaner**:

- [x] Выполнение Lua-выражений.
- [x] Выполнение Lua-скриптов.
- [x] Начальная конфигурация (задание директори с исходными кодами, задание имени скрипта для запуска, задание уровня логирования, задание количества памяти, пользователь).
- [ ] Изменение конфигурации на работающем контейнере.
- [x] Обработка версий.
- [ ] Использование фиксированных портов.
- [ ] Проверка работы при некорректной начальной конфигурации.
- [ ] Проверка работы при некорректной конфигурации после запуска контейнера.
- [x] Работа с SSL, mTLS.

**TarantoolCartridgeContainer**

- [x] Простой запуск
- [x] Проверка начальной конфигурации: cookie.
- [x] Установка топологии: Lua
- [x] Установка топологии: Yaml 
- [x] Аргументы сборки образа.
- [x] Работа с фиксированными портами.
- [ ] Ошибки начальной конфигурации.
- [ ] Изменение конфигурации в ходе работы.
- [ ] Изменение топологии.
- [ ] Остановка и запуск отдельных узлов.

**Comment by bitgorbovsky** [comment]
Другие исследования: https://github.com/tarantool/testcontainers-java-tarantool/issues/85

**Comment by bitgorbovsky** [comment]
# Необходимость в других типах контейнеров

В спайке #85 была предпринята попытка выделить тип контейнера TarantoolNodeContainer (или TarantoolSimpleContainer), который реализует поднятие контейнера и его конфигурирование, а также предлагалсь обёртка TarantoolCluster, которая запускает набор таких "простых" контейнеров (в одной сети). Данная реализация позволит проверять поведение тестируемого приложения, в случае, если один из узлов кластера испытывает проблемы с сетью (в отдельном контейнере можно запустить команды, эмулирующие проблемы сети).

TarantoolCartridgeContainer удобен как способ быстро поднять приложение cartridge, но он более ограниченный. Предполагается, что сочетание TarantoolNodeContainer + TarantoolCluster может его заменить. Трудоёмкость реализации оценивается в 5+ SP.

Другие типы контейнеров нет необходимости вводить.

**Comment by bitgorbovsky** [comment]
# Предложения по рефакторингу кода

* Упорядочить методы в TarantoolCartridgeContainer, сначала static, затем затем конструкторы и public, затем protected и private.
* Добавить Builder. Текущая реализация сейчас опирается на методы конфигурирования with<OptionName>, что приводит к визуальной путанице.
* Убрать всё, что связано с подключением папок. Если нужно подключать папки к контейнеру для какой-то причины, то можно обойтись Java Docker API
* Улучшить TarantoolContainerImageHelper:
   - убрать валидацию параметров для TarantoolImageParams, перенести её в TarantoolImageParams;
   - улучшить читаемость кода
* Улучшить TarantoolImageParams:
  - Усилить валидацию аргументов конструктора

Возможно, классы TarantoolContainerImageHelper и TarantoolImageParams объедить в класс TarantoolDockerImage, который будет отвечать за сборку образа, со всеми параметрами, и который будет предоставлять параметры образа классу, занимающему запуском контейнеров. Таким образом, разделить ответственности классов - TarantoolDockerImage занимается сборкой образа, а TarantoolContainer запускает контейнер на основе образе.

**Comment by dkasimovskiy** [comment]
Вернемся к этому вопросу при планировании 2024Q2
