### ISSUE TITLE
Mention TARANTOOL_SERVER_USERNAME and other env options in README

### ISSUE THREAD

**Issue by akudiyar** [tarantool/testcontainers-java-tarantool#12]
subj

**Comment by vrogach2020** [comment]
This step is required:
To execute cluster tests you need to do:
export TARANTOOL_SERVER_USER=<current_user>
export TARANTOOL_SERVER_GROUP=<current_user_group>

**Comment by dkasimovskiy** [comment]
Need to double check do we steel need those variables.
