### ISSUE TITLE
Can not connect to router with cartridge 2.7.4

### ISSUE THREAD

**Issue by iDneprov** [tarantool/testcontainers-java-tarantool#53]
When starting Testcontainer with cartridge 2.7.4 application I get an error: can't connect to the router.

**Comment by dkasimovskiy** [comment]
Need to double check with version 1.0.0+ and Cartridge 2.8+

**Comment by dkasimovskiy** [comment]
Also we can force advertise_uri as 0.0.0.0 rather than 127.0.0.1 in the instance.yml

**Comment by bitgorbovsky** [comment]
It works with Cartridge version 2.8+ perfectly.
And we have to use 0.0.0.0 network interface instead of pointing to localhost.
Checked also in cartridge-java with version of cartridge 2.7.4 and it also passes tests.
